services:
  app:
  build: .
  container_name: syl_api_app
  restart: unless-stopped
  ports:
    - "3000:3000"
  environment:
    NODE_ENV: development
    MONGO_URI: "mongodb://syl_user:syl_pass@mongodb:27017/syl?authSource=admin"
  depends_on:
    - mongodb
  volumes:
    - ./:/usr/src/app
  command: npm run start:dev

  mongodb:
  image: mongo:6
  container_name: syl_api_mongodb
  restart: unless-stopped
  environment:
    MONGO_INITDB_ROOT_USERNAME: syl_user
    MONGO_INITDB_ROOT_PASSWORD: syl_pass
  volumes:
    - mongodb_data:/data/db
  ports:
    - "27017:27017"